### ISSUE TITLE
Help with installing on Mac

### ISSUE THREAD

**Issue by oakif** [mphoward/gsd-vmd#6]
Hello! I apologize for the basic question, but I'm trying to figure out how to install this plugin on Catalina. I'm stuck at the step where I need to specify the VMD plugin directory—I never installed a VMD plugin before. I'm also not sure where the plugin headers and system-specific molfile libraries reside. These need to be defined when using `cmake`.

**Comment by mphoward** [comment]
Plugins get installed into the same location as VMD. You should know where you installed VMD on your version of macOS (since you are also using Catalina, I guess it is a port)... it is probably somewhere in your Applications.

From the README:

> VMD_PLUGIN_INCLUDE_PATH and VMD_PLUGIN_MOLFILE_PATH. These directories are the location of your plugin headers (e.g., molfile_plugin.h) and system-specific molfile libraries, respectively.

So, within your VMD installation, you need to do a find for `molfile_plugin.h`, which gives the `VMD_PLUGIN_INCLUDE_PATH` and for any built-in plugin like `xyzplugin.so`, which gives the `VMD_PLUGIN_MOLFILE_PATH`.

I would recommend trying to point to the VMD installation with `VMDDIR` first, though, as cmake can do this search automatically with the right hints. `VMDDIR` points to the base `vmd` directory that is common to Linux and macOS. The default guess for `VMDDIR` is `/Applications/*/Contents/vmd` on macOS, but you should set it to the appropriate value for your system, either as an env var or with `-DVMDDIR`.

**Comment by oakif** [comment]
Thanks a lot! That worked. It turns out I didn't realize that the Applications folder was the "installation" directory. If anyone else comes into this issue, just type in `VMDDIR=/Applications` after dragging the `.app` to your default Applications directory. `cmake` takes care of the rest; the plugins directory is a inside a subfolder of the `.app` in your Applications folder.
